name: Deploy Raven Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ensures the bot has write access

    steps:
    # Step 1: Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust based on site requirements

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install || echo "No dependencies to install"

    # Step 4: Build the Site
    - name: Build Website
      run: npm run build || echo "No build script defined, skipping"

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # Adjust based on your output directory
