name: Deploy Raven Pages

on:
  push:
    branches:
      - main  # Trigger deployment whenever the main branch is pushed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Added to ensure the workflow can write to the repository

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if your site requires a different Node.js version

      # Step 3: Clear npm cache - to ensure we're using the latest dependencies
      - name: Clear npm cache
        run: npm cache clean --force

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Build the Site
      - name: Build Website
        run: npm run build

      # Step 6: Check contents of the build folder
      - name: List files in build folder
        run: |
          echo "Listing build directory:"
          ls -la ./build

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Publishes the build directory to the root of the gh-pages branch
          publish_branch: gh-pages
          keep_files: false
